---
name: "rgbank"
tasks:
  - "servicenow_tasks::create_record"
plans:
  - "dev_env::provision"
  - "dev_env::deprovision"
  - "terraform::apply"
  - "terraform::destroy"
  - "rgbank::develop"
roles:
  - "rgbank"
  - "rgbank::web"
  - "rgbank::db" 
  - "rgbank::docker"
